import { Airplay, AlertCircle, AlertOctagon, AlertTriangle, AlignCenter, AlignJustify, AlignLeft, AlignRight, Anchor, Aperture, Archive, ArrowDownCircle, ArrowDownLeft, ArrowDownRight, ArrowDown, ArrowLeftCircle, ArrowLeft, ArrowRightCircle, ArrowRight, ArrowUpCircle, ArrowUpLeft, ArrowUpRight, ArrowUp, AtSign, Award, BatteryCharging, BatteryFull, BatteryLow, BatteryMedium, Beaker, BellOff, Bell, Bluetooth, Bold, BookOpen, Book, Bookmark, Box, Briefcase, Calendar, CameraOff, Camera, Cast, CheckCircle, CheckSquare, Check, ChevronDown, ChevronLeft, ChevronRight, ChevronUp, ChevronsDown, ChevronsLeft, ChevronsRight, ChevronsUp, Chrome, Circle, Clipboard, Clock, CloudDrizzle, CloudLightning, CloudOff, CloudRain, CloudSnow, Cloud, Code, Codepen, Codesandbox, Coffee, Columns, Command, Compass, Copy, CornerDownLeft, CornerDownRight, CornerLeftDown, CornerLeftUp, CornerRightDown, CornerRightUp, CornerUpLeft, CornerUpRight, Cpu, CreditCard, Crop, Crosshair, Database, Delete, Disc, DollarSign, DownloadCloud, Download, Edit, ExternalLink, EyeOff, Eye, Facebook, FastForward, Feather, FileMinus, FilePlus, FileText, File, Film, Filter, Flag, FolderMinus, FolderPlus, Folder, Framer, GitBranch, GitCommit, GitMerge, GitPullRequest, Github, Gitlab, Globe, Grid, HardDrive, Hash, Headphones, Heart, HelpCircle, Home, Image, Inbox, Instagram, Italic, Key, Layers, Layout, LifeBuoy, Link2, Link, Linkedin, List, Loader, Lock, LogIn, LogOut, Mail, MapPin, Map, Maximize2, Maximize, Meh, Menu, MessageCircle, MessageSquare, MicOff, Mic, Minimize2, Minimize, MinusCircle, MinusSquare, Minus, Monitor, Moon, MoreHorizontal, MoreVertical, MousePointer, Move, Music, Navigation, Navigation2, Network, Octagon, Package, Paperclip, PauseCircle, Pause, PlayCircle, Play, PlusCircle, PlusSquare, Plus, Pocket, Power, Printer, Radio, RefreshCcw, RefreshCw, Rewind, RotateCcw, RotateCw, Rss, Save, Scissors, Search, Send, Server, Settings, Share2, Share, ShieldOff, Shield, ShoppingBag, ShoppingCart, Shuffle, Sidebar, SkipBack, SkipForward, Slack, Slash, Sliders, Smartphone, Speaker, Square, Star, StopCircle, Sun, Sunrise, Sunset, Tablet, Tag, Target, Terminal, Thermometer, ThumbsDown, ThumbsUp, ToggleLeft, ToggleRight, Trash, Trello, TrendingDown, TrendingUp, Triangle, Truck, Tv, Twitter, Type, Umbrella, Unlink, UploadCloud, Upload, UserCheck, UserMinus, UserPlus, UserX, User, Users, VideoOff, Video, Voicemail, Volume1, Volume2, VolumeX, Volume, WifiOff, Wifi, Wind, XCircle, XSquare, X, Youtube } from 'lucide-react';

const iconMapping = {
  airplay: Airplay,
  alertCircle: AlertCircle,
  alertOctagon: AlertOctagon,
  alertTriangle: AlertTriangle,
  alignCenter: AlignCenter,
  alignJustify: AlignJustify,
  alignLeft: AlignLeft,
  alignRight: AlignRight,
  anchor: Anchor,
  aperture: Aperture,
  archive: Archive,
  arrowDownCircle: ArrowDownCircle,
  arrowDownLeft: ArrowDownLeft,
  arrowDownRight: ArrowDownRight,
  arrowDown: ArrowDown,
  arrowLeftCircle: ArrowLeftCircle,
  arrowLeft: ArrowLeft,
  arrowRightCircle: ArrowRightCircle,
  arrowRight: ArrowRight,
  arrowUpCircle: ArrowUpCircle,
  arrowUpLeft: ArrowUpLeft,
  arrowUpRight: ArrowUpRight,
  arrowUp: ArrowUp,
  atSign: AtSign,
  award: Award,
  batteryCharging: BatteryCharging,
  batteryFull: BatteryFull,
  batteryLow: BatteryLow,
  batteryMedium: BatteryMedium,
  beaker: Beaker,
  bellOff: BellOff,
  bell: Bell,
  bluetooth: Bluetooth,
  bold: Bold,
  bookOpen: BookOpen,
  book: Book,
  bookmark: Bookmark,
  box: Box,
  briefcase: Briefcase,
  calendar: Calendar,
  cameraOff: CameraOff,
  camera: Camera,
  cast: Cast,
  checkCircle: CheckCircle,
  checkSquare: CheckSquare,
  check: Check,
  chevronDown: ChevronDown,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronUp: ChevronUp,
  chevronsDown: ChevronsDown,
  chevronsLeft: ChevronsLeft,
  chevronsRight: ChevronsRight,
  chevronsUp: ChevronsUp,
  chrome: Chrome,
  circle: Circle,
  clipboard: Clipboard,
  clock: Clock,
  cloudDrizzle: CloudDrizzle,
  cloudLightning: CloudLightning,
  cloudOff: CloudOff,
  cloudRain: CloudRain,
  cloudSnow: CloudSnow,
  cloud: Cloud,
  code: Code,
  codepen: Codepen,
  codesandbox: Codesandbox,
  coffee: Coffee,
  columns: Columns,
  command: Command,
  compass: Compass,
  copy: Copy,
  cornerDownLeft: CornerDownLeft,
  cornerDownRight: CornerDownRight,
  cornerLeftDown: CornerLeftDown,
  cornerLeftUp: CornerLeftUp,
  cornerRightDown: CornerRightDown,
  cornerRightUp: CornerRightUp,
  cornerUpLeft: CornerUpLeft,
  cornerUpRight: CornerUpRight,
  cpu: Cpu,
  creditCard: CreditCard,
  crop: Crop,
  crosshair: Crosshair,
  database: Database,
  delete: Delete,
  disc: Disc,
  dollarSign: DollarSign,
  downloadCloud: DownloadCloud,
  download: Download,
  edit: Edit,
  externalLink: ExternalLink,
  eyeOff: EyeOff,
  eye: Eye,
  facebook: Facebook,
  fastForward: FastForward,
  feather: Feather,
  fileMinus: FileMinus,
  filePlus: FilePlus,
  fileText: FileText,
  file: File,
  film: Film,
  filter: Filter,
  flag: Flag,
  folderMinus: FolderMinus,
  folderPlus: FolderPlus,
  folder: Folder,
  framer: Framer,
  gitBranch: GitBranch,
  gitCommit: GitCommit,
  gitMerge: GitMerge,
  gitPullRequest: GitPullRequest,
  github: Github,
  gitlab: Gitlab,
  globe: Globe,
  grid: Grid,
  hardDrive: HardDrive,
  hash: Hash,
  headphones: Headphones,
  heart: Heart,
  helpCircle: HelpCircle,
  home: Home,
  image: Image,
  inbox: Inbox,
  instagram: Instagram,
  italic: Italic,
  key: Key,
  layers: Layers,
  layout: Layout,
  lifeBuoy: LifeBuoy,
  link2: Link2,
  link: Link,
  linkedin: Linkedin,
  list: List,
  loader: Loader,
  lock: Lock,
  logIn: LogIn,
  logOut: LogOut,
  mail: Mail,
  mapPin: MapPin,
  map: Map,
  maximize2: Maximize2,
  maximize: Maximize,
  meh: Meh,
  menu: Menu,
  messageCircle: MessageCircle,
  messageSquare: MessageSquare,
  micOff: MicOff,
  mic: Mic,
  minimize2: Minimize2,
  minimize: Minimize,
  minusCircle: MinusCircle,
  minusSquare: MinusSquare,
  minus: Minus,
  monitor: Monitor,
  moon: Moon,
  moreHorizontal: MoreHorizontal,
  moreVertical: MoreVertical,
  mousePointer: MousePointer,
  move: Move,
  music: Music,
  navigation: Navigation,
  navigation2: Navigation2,
  network: Network,
  octagon: Octagon,
  package: Package,
  paperclip: Paperclip,
  pauseCircle: PauseCircle,
  pause: Pause,
  playCircle: PlayCircle,
  play: Play,
  plusCircle: PlusCircle,
  plusSquare: PlusSquare,
  plus: Plus,
  pocket: Pocket,
  power: Power,
  printer: Printer,
  radio: Radio,
  refreshCcw: RefreshCcw,
  refreshCw: RefreshCw,
  rewind: Rewind,
  rotateCcw: RotateCcw,
  rotateCw: RotateCw,
  rss: Rss,
  save: Save,
  scissors: Scissors,
  search: Search,
  send: Send,
  server: Server,
  settings: Settings,
  share2: Share2,
  share: Share,
  shieldOff: ShieldOff,
  shield: Shield,
  shoppingBag: ShoppingBag,
  shoppingCart: ShoppingCart,
  shuffle: Shuffle,
  sidebar: Sidebar,
  skipBack: SkipBack,
  skipForward: SkipForward,
  slack: Slack,
  slash: Slash,
  sliders: Sliders,
  smartphone: Smartphone,
  speaker: Speaker,
  square: Square,
  star: Star,
  stopCircle: StopCircle,
  sun: Sun,
  sunrise: Sunrise,
  sunset: Sunset,
  tablet: Tablet,
  tag: Tag,
  target: Target,
  terminal: Terminal,
  thermometer: Thermometer,
  thumbsDown: ThumbsDown,
  thumbsUp: ThumbsUp,
  toggleLeft: ToggleLeft,
  toggleRight: ToggleRight,
  trash: Trash,
  trello: Trello,
  trendingDown: TrendingDown,
  trendingUp: TrendingUp,
  triangle: Triangle,
  truck: Truck,
  tv: Tv,
  twitter: Twitter,
  type: Type,
  umbrella: Umbrella,
  unlink: Unlink,
  uploadCloud: UploadCloud,
  upload: Upload,
  userCheck: UserCheck,
  userMinus: UserMinus,
  userPlus: UserPlus,
  userX: UserX,
  user: User,
  users: Users,
  videoOff: VideoOff,
  video: Video,
  voicemail: Voicemail,
  volume1: Volume1,
  volume2: Volume2,
  volumeX: VolumeX,
  volume: Volume,
  wifiOff: WifiOff,
  wifi: Wifi,
  wind: Wind,
  xCircle: XCircle,
  xSquare: XSquare,
  x: X,
  youtube: Youtube
};

type Props = {
  onSelect: (icono: string) => void;  // Pasamos el nombre del ícono seleccionado
  onClose: () => void;
};

export default function ModalSeleccionIcono({ onSelect, onClose }: Props) {
  return (
    <div
      style={{
        position: 'fixed',
        top: 0,
        left: 0,
        width: '100vw',
        height: '100vh',
        backgroundColor: 'rgba(0,0,0,0.5)',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        zIndex: 9999,
      }}
      onClick={onClose}
    >
      <div
        onClick={(e) => e.stopPropagation()}  // Evitar que el modal se cierre al hacer clic dentro del modal
        style={{
          backgroundColor: 'white',
          maxHeight: '80vh',
          maxWidth: '80vw',
          overflow: 'auto',
          padding: 20,
          borderRadius: 8,
          display: 'grid',
          gridTemplateColumns: 'repeat(auto-fill, minmax(64px, 1fr))',
          gap: 12,
        }}
      >
        {/* Iteramos sobre el mapeo de íconos */}
        {Object.entries(iconMapping).map(([key, IconComponent]) => (
          <div
            key={key}
            onClick={() => onSelect(key)}  // Seleccionamos el nombre del ícono
            title={key}
            style={{
              display: 'flex',
              flexDirection: 'column',
              alignItems: 'center',
              cursor: 'pointer',
              fontSize: 10,
              color: '#333',
            }}
          >
            {/* Renderizamos el componente ícono */}
            <IconComponent size={24} />
            <span style={{ marginTop: 4 }}>{key}</span>
          </div>
        ))}
      </div>
    </div>
  );
}
