// ✅ Versión completa de BottomNavbarComp con soporte para íconos, texto responsive y estilo activo

import React from 'react';
import { Airplay, AlertCircle, AlertOctagon, AlertTriangle, AlignCenter, AlignJustify, AlignLeft, AlignRight, Anchor, Aperture, Archive, ArrowDownCircle, ArrowDownLeft, ArrowDownRight, ArrowDown, ArrowLeftCircle, ArrowLeft, ArrowRightCircle, ArrowRight, ArrowUpCircle, ArrowUpLeft, ArrowUpRight, ArrowUp, AtSign, Award, BatteryCharging, BatteryFull, BatteryLow, BatteryMedium, Beaker, BellOff, Bell, Bluetooth, Bold, BookOpen, Book, Bookmark, Box, Briefcase, Calendar, CameraOff, Camera, Cast, CheckCircle, CheckSquare, Check, ChevronDown, ChevronLeft, ChevronRight, ChevronUp, ChevronsDown, ChevronsLeft, ChevronsRight, ChevronsUp, Chrome, Circle, Clipboard, Clock, CloudDrizzle, CloudLightning, CloudOff, CloudRain, CloudSnow, Cloud, Code, Codepen, Codesandbox, Coffee, Columns, Command, Compass, Copy, CornerDownLeft, CornerDownRight, CornerLeftDown, CornerLeftUp, CornerRightDown, CornerRightUp, CornerUpLeft, CornerUpRight, Cpu, CreditCard, Crop, Crosshair, Database, Delete, Disc, DollarSign, DownloadCloud, Download, Edit, ExternalLink, EyeOff, Eye, Facebook, FastForward, Feather, FileMinus, FilePlus, FileText, File, Film, Filter, Flag, FolderMinus, FolderPlus, Folder, Framer, GitBranch, GitCommit, GitMerge, GitPullRequest, Github, Gitlab, Globe, Grid, HardDrive, Hash, Headphones, Heart, HelpCircle, Home, Image, Inbox, Instagram, Italic, Key, Layers, Layout, LifeBuoy, Link2, Link, Linkedin, List, Loader, Lock, LogIn, LogOut, Mail, MapPin, Map, Maximize2, Maximize, Meh, Menu, MessageCircle, MessageSquare, MicOff, Mic, Minimize2, Minimize, MinusCircle, MinusSquare, Minus, Monitor, Moon, MoreHorizontal, MoreVertical, MousePointer, Move, Music, Navigation, Navigation2, Network, Octagon, Package, Paperclip, PauseCircle, Pause, PlayCircle, Play, PlusCircle, PlusSquare, Plus, Pocket, Power, Printer, Radio, RefreshCcw, RefreshCw, Rewind, RotateCcw, RotateCw, Rss, Save, Scissors, Search, Send, Server, Settings, Share2, Share, ShieldOff, Shield, ShoppingBag, ShoppingCart, Shuffle, Sidebar, SkipBack, SkipForward, Slack, Slash, Sliders, Smartphone, Speaker, Square, Star, StopCircle, Sun, Sunrise, Sunset, Tablet, Tag, Target, Terminal, Thermometer, ThumbsDown, ThumbsUp, ToggleLeft, ToggleRight, Trash, Trello, TrendingDown, TrendingUp, Triangle, Truck, Tv, Twitter, Type, Umbrella, Unlink, UploadCloud, Upload, UserCheck, UserMinus, UserPlus, UserX, User, Users, VideoOff, Video, Voicemail, Volume1, Volume2, VolumeX, Volume, WifiOff, Wifi, Wind, XCircle, XSquare, X, Youtube } from 'lucide-react';
import type { LucideIcon } from 'lucide-react';

// Definición de tipo para cada ítem
type Item = {
  label: string;
  nombrePestana: string;
  icono?: string; // ← icono opcional por nombre
};

const iconMap: Record<string, LucideIcon> = {
  airplay: Airplay,
  alertCircle: AlertCircle,
  alertOctagon: AlertOctagon,
  alertTriangle: AlertTriangle,
  alignCenter: AlignCenter,
  alignJustify: AlignJustify,
  alignLeft: AlignLeft,
  alignRight: AlignRight,
  anchor: Anchor,
  aperture: Aperture,
  archive: Archive,
  arrowDownCircle: ArrowDownCircle,
  arrowDownLeft: ArrowDownLeft,
  arrowDownRight: ArrowDownRight,
  arrowDown: ArrowDown,
  arrowLeftCircle: ArrowLeftCircle,
  arrowLeft: ArrowLeft,
  arrowRightCircle: ArrowRightCircle,
  arrowRight: ArrowRight,
  arrowUpCircle: ArrowUpCircle,
  arrowUpLeft: ArrowUpLeft,
  arrowUpRight: ArrowUpRight,
  arrowUp: ArrowUp,
  atSign: AtSign,
  award: Award,
  batteryCharging: BatteryCharging,
  batteryFull: BatteryFull,
  batteryLow: BatteryLow,
  batteryMedium: BatteryMedium,
  beaker: Beaker,
  bellOff: BellOff,
  bell: Bell,
  bluetooth: Bluetooth,
  bold: Bold,
  bookOpen: BookOpen,
  book: Book,
  bookmark: Bookmark,
  box: Box,
  briefcase: Briefcase,
  calendar: Calendar,
  cameraOff: CameraOff,
  camera: Camera,
  cast: Cast,
  checkCircle: CheckCircle,
  checkSquare: CheckSquare,
  check: Check,
  chevronDown: ChevronDown,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronUp: ChevronUp,
  chevronsDown: ChevronsDown,
  chevronsLeft: ChevronsLeft,
  chevronsRight: ChevronsRight,
  chevronsUp: ChevronsUp,
  chrome: Chrome,
  circle: Circle,
  clipboard: Clipboard,
  clock: Clock,
  cloudDrizzle: CloudDrizzle,
  cloudLightning: CloudLightning,
  cloudOff: CloudOff,
  cloudRain: CloudRain,
  cloudSnow: CloudSnow,
  cloud: Cloud,
  code: Code,
  codepen: Codepen,
  codesandbox: Codesandbox,
  coffee: Coffee,
  columns: Columns,
  command: Command,
  compass: Compass,
  copy: Copy,
  cornerDownLeft: CornerDownLeft,
  cornerDownRight: CornerDownRight,
  cornerLeftDown: CornerLeftDown,
  cornerLeftUp: CornerLeftUp,
  cornerRightDown: CornerRightDown,
  cornerRightUp: CornerRightUp,
  cornerUpLeft: CornerUpLeft,
  cornerUpRight: CornerUpRight,
  cpu: Cpu,
  creditCard: CreditCard,
  crop: Crop,
  crosshair: Crosshair,
  database: Database,
  delete: Delete,
  disc: Disc,
  dollarSign: DollarSign,
  downloadCloud: DownloadCloud,
  download: Download,
  edit: Edit,
  externalLink: ExternalLink,
  eyeOff: EyeOff,
  eye: Eye,
  facebook: Facebook,
  fastForward: FastForward,
  feather: Feather,
  fileMinus: FileMinus,
  filePlus: FilePlus,
  fileText: FileText,
  file: File,
  film: Film,
  filter: Filter,
  flag: Flag,
  folderMinus: FolderMinus,
  folderPlus: FolderPlus,
  folder: Folder,
  framer: Framer,
  gitBranch: GitBranch,
  gitCommit: GitCommit,
  gitMerge: GitMerge,
  gitPullRequest: GitPullRequest,
  github: Github,
  gitlab: Gitlab,
  globe: Globe,
  grid: Grid,
  hardDrive: HardDrive,
  hash: Hash,
  headphones: Headphones,
  heart: Heart,
  helpCircle: HelpCircle,
  home: Home,
  image: Image,
  inbox: Inbox,
  instagram: Instagram,
  italic: Italic,
  key: Key,
  layers: Layers,
  layout: Layout,
  lifeBuoy: LifeBuoy,
  link2: Link2,
  link: Link,
  linkedin: Linkedin,
  list: List,
  loader: Loader,
  lock: Lock,
  logIn: LogIn,
  logOut: LogOut,
  mail: Mail,
  mapPin: MapPin,
  map: Map,
  maximize2: Maximize2,
  maximize: Maximize,
  meh: Meh,
  menu: Menu,
  messageCircle: MessageCircle,
  messageSquare: MessageSquare,
  micOff: MicOff,
  mic: Mic,
  minimize2: Minimize2,
  minimize: Minimize,
  minusCircle: MinusCircle,
  minusSquare: MinusSquare,
  minus: Minus,
  monitor: Monitor,
  moon: Moon,
  moreHorizontal: MoreHorizontal,
  moreVertical: MoreVertical,
  mousePointer: MousePointer,
  move: Move,
  music: Music,
  navigation: Navigation,
  navigation2: Navigation2,
  network: Network,
  octagon: Octagon,
  package: Package,
  paperclip: Paperclip,
  pauseCircle: PauseCircle,
  pause: Pause,
  playCircle: PlayCircle,
  play: Play,
  plusCircle: PlusCircle,
  plusSquare: PlusSquare,
  plus: Plus,
  pocket: Pocket,
  power: Power,
  printer: Printer,
  radio: Radio,
  refreshCcw: RefreshCcw,
  refreshCw: RefreshCw,
  rewind: Rewind,
  rotateCcw: RotateCcw,
  rotateCw: RotateCw,
  rss: Rss,
  save: Save,
  scissors: Scissors,
  search: Search,
  send: Send,
  server: Server,
  settings: Settings,
  share2: Share2,
  share: Share,
  shieldOff: ShieldOff,
  shield: Shield,
  shoppingBag: ShoppingBag,
  shoppingCart: ShoppingCart,
  shuffle: Shuffle,
  sidebar: Sidebar,
  skipBack: SkipBack,
  skipForward: SkipForward,
  slack: Slack,
  slash: Slash,
  sliders: Sliders,
  smartphone: Smartphone,
  speaker: Speaker,
  square: Square,
  star: Star,
  stopCircle: StopCircle,
  sun: Sun,
  sunrise: Sunrise,
  sunset: Sunset,
  tablet: Tablet,
  tag: Tag,
  target: Target,
  terminal: Terminal,
  thermometer: Thermometer,
  thumbsDown: ThumbsDown,
  thumbsUp: ThumbsUp,
  toggleLeft: ToggleLeft,
  toggleRight: ToggleRight,
  trash: Trash,
  trello: Trello,
  trendingDown: TrendingDown,
  trendingUp: TrendingUp,
  triangle: Triangle,
  truck: Truck,
  tv: Tv,
  twitter: Twitter,
  type: Type,
  umbrella: Umbrella,
  unlink: Unlink,
  uploadCloud: UploadCloud,
  upload: Upload,
  userCheck: UserCheck,
  userMinus: UserMinus,
  userPlus: UserPlus,
  userX: UserX,
  user: User,
  users: Users,
  videoOff: VideoOff,
  video: Video,
  voicemail: Voicemail,
  volume1: Volume1,
  volume2: Volume2,
  volumeX: VolumeX,
  volume: Volume,
  wifiOff: WifiOff,
  wifi: Wifi,
  wind: Wind,
  xCircle: XCircle,
  xSquare: XSquare,
  x: X,
  youtube: Youtube
};
// Props del componente
type Props = {
  items?: Item[];
  selectedIndex?: number;
  fontSize?: number; // ← valor normalizado (0–1)
  iconSize?: number; // ← valor normalizado (0–1)
  colorActivo?: string;
  colorInactivo?: string;
  fondo?: string;
  borderRadius?: number;
  zoom: number;
  canvasHeight: number;
};

const BottomNavbarComp: React.FC<Props> = ({
  items = [
    { label: 'Inicio', nombrePestana: 'Pantalla 1', icono: 'home' },
    { label: 'Mensajes', nombrePestana: 'Pantalla 2', icono: 'message' },
    { label: 'Perfil', nombrePestana: 'Pantalla 3', icono: 'user' },
  ],
  selectedIndex = 0,
  fontSize = 0.02,
    iconSize = 0.02,       // Tamaño del icono
  colorActivo = '#2563eb',
  colorInactivo = '#666',
  fondo = '#fff',
  borderRadius = 0,
  zoom,
  canvasHeight,
}) => {
  const pixelFontSize = fontSize * canvasHeight * zoom;
    const pixelIconSize = iconSize * canvasHeight * zoom;  // Tamaño de icono
  return (
    <div
      className="no-drag"
      style={{
        display: 'flex',
        width: '100%',
        height: '100%',
        backgroundColor: fondo,
        border: '1px solid #ccc',
        borderRadius: borderRadius * zoom,
        overflow: 'hidden',
      }}
    >
      {items.map((item, index) => {
        const Icon = item.icono ? iconMap[item.icono] : null;

        return (
          <div
            key={index}
            style={{
              flex: 1,
              display: 'flex',
              flexDirection: 'column',
              alignItems: 'center',
              justifyContent: 'center',
              padding: `${6 * zoom}px 0`,
              fontSize: pixelFontSize,
              color: index === selectedIndex ? colorActivo : colorInactivo,
              fontWeight: index === selectedIndex ? 'bold' : 'normal',
              borderTop:
                index === selectedIndex
                  ? `2px solid ${colorActivo}`
                  : '2px solid transparent',
              cursor: 'default',
              userSelect: 'none',
              pointerEvents: 'none',
            }}
          >
            {Icon && <Icon size={pixelIconSize} strokeWidth={1.5} />}
            <span style={{ marginTop: 2 }}>{item.label}</span>
          </div>
        );
      })}
    </div>
  );
};

export default BottomNavbarComp;
